kind: pipeline
type: exec
name: deploy

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
    - docker build -t gotify-telegram .
  when:
  branch:
      - master

- name: run
  commands:
    - cd /var/docker/gotify-telegram
    #- docker-compose stop gotify-telegram
    - docker-compose up -d gotify-telegram
  when:
  branch:
    - master